### ISSUE TITLE
SDL_GAMECONTROLLERCONFIG on Linux

### ISSUE THREAD

**Issue by TiZ-EX1** [pbhogan/InControl#183]
Hi there. I'm not sure if I have any right to be filing this bug report; I'm a player of games that use this library (to be specific, Heart&Slash and soon JumpJet Rex), rather than a user of the library itself. On Linux, there is a standard mechanism for mapping any controller to the Xbox 360 layout. SDL2 was the first to provide support for it, and Steam standardized around it.

The SDL_GAMECONTROLLERCONFIG environment variable has mappings for any number of controllers to the 360 layout. An example of the format, as well as a repo of already configured mappings, can be found at https://github.com/gabomdq/SDL_GameControllerDB.

The more important thing is that this environment variable is the way that regular users map their controllers. Steam sets this environment variable when starting the game from the mappings that are made in big picture mode. And of course, there are other ways a user can configure this without Steam.

All SDL2 games (basically all non-Unity games) respect this variable and controllers work as expected when the mappings are there. Unity doesn't respect the variable at all yet, it just assumes every controller is a 360 controller. And apparently InControl is somewhere else. Heart&Slash just won't work with non-360 controllers unless I make a special text configuration. I shouldn't have to make yet another configuration; please just use the established standard.

**Comment by pbhogan** [comment]
Hi Trent,

InControl is currently built as a layer on top of Unity so I have no further control than what they do. Incidentally, I don't think they consider every controller a 360 controller since I have mappings for several controllers on Linux on top of Unity's input system. 

However, I can tell you Unity is working on a new input system to be released sometime in the coming year I think and I know they are putting effort into the Linux support and particularly using SDL and Steam mappings. I have no more information than this unfortunately, but at least they are planning to address the issue.

**Comment by TiZ-EX1** [comment]
Are you not able to access environment variables?

**Comment by pbhogan** [comment]
No, and even if I could I can't apply it since I don't have access to the Vendor and Product IDs which the mappings are based on. There is no way I can currently make this work with Unity's input system.

**Comment by TiZ-EX1** [comment]
Okay, thank you for your time anyways. :)

**Comment by Cheeseness** [comment]
FWIW, [Unity 5 accepts](https://plus.google.com/104339689434081533648/posts/d3oBCgkthDT) (Levi Bard is one of Unity's Linux developers) or will accept - I haven't fiddled with the beta yet - SDL style bindings, and read/respect SDL_GAMECONTROLLERCONFIG.

**Comment by TiZ-EX1** [comment]
Right, and that's great, but some developers are understandably afraid to migrate.

**Comment by Cheeseness** [comment]
Definitely. It's a big overhead to incur late in development.

Those games are pretty much a lost cause so far as far as this issue goes, I guess (just like games effected by the pre-4.5.2 windowing/mouse input problems on Linux whose developers didn't upgrade).
