### ISSUE TITLE
Inverted DPad - InControl beta

### ISSUE THREAD

**Issue by bogdanrybak** [pbhogan/InControl#186]
Using beta 1.5.0 b4403. The direction given by the DPad is Y-inverted opposite to the sticks.Tracked it down to the new UnityInputDeviceProfile.cs and swapped the SourceRange / TargetRange between the two methods.

**Comment by pbhogan** [comment]
For which device / profile / platform?

This would be a device specific incorrect mapping, so don't change it in UnityInputDeviceProfile.cs

**Comment by bogdanrybak** [comment]
Xbox360WinProfile.cs, the mapping seems to be correct there since up and down are mapping to the same axis.

Shouldn't these be other way around?
```
		protected static InputControlMapping DPadUpMapping( InputControlSource analog )
		{
			return new InputControlMapping {
				Handle = "DPad Up",
				Target = InputControlType.DPadUp,
				Source = analog,
				SourceRange = InputRange.ZeroToMinusOne,
				TargetRange = InputRange.ZeroToOne
			};
		}

		protected static InputControlMapping DPadDownMapping( InputControlSource analog )
		{
			return new InputControlMapping {
				Handle = "DPad Down",
				Target = InputControlType.DPadDown,
				Source = analog,
				SourceRange = InputRange.ZeroToOne,
				TargetRange = InputRange.ZeroToOne
			};
		}
```

**Comment by pbhogan** [comment]
No, it's correct for many other controllers. It just means the mapping needs to not use this shortcut method and explicitly create the mappings the other way around in the profile.

**Comment by bogdanrybak** [comment]
Understood, I will change the mapping within the Xbox360 profile. I can confirm this is also the case with the F310.

**Comment by pbhogan** [comment]
Okay, I'll check them and any other controllers I have and update appropriately for the next update. Thanks!
