### ISSUE TITLE
Playstation 4 mappings Playstation4AndoridProfile.cs contains invalid button "Start"

### ISSUE THREAD

**Issue by mrkake** [pbhogan/InControl#188]
Hi,
I was taking a look at the PS4 mapping profiles. I noticed that the PlayStation4AndroidProfile.cs contains the following:  

new InputControlMapping {
					Handle = "Start",
					Target = InputControlType.Start,
					Source = Button7
				},

this is not a valid button on the ps4 controller, and this entry does not exist in the other PS4 mappings. Also it is unclear what Button7 actual is, since there also exists a mapping for "Options" (what is the closest to 'start' on the ps4) as Button6.

**Comment by pbhogan** [comment]
Hmm. That's a user submitted profile so I'm not too sure... it's either the Share button or the PlayStation button—I'd guess Share. Either way it's misnamed and they probably went by position left to right. I'll take a look and see if I can connect one to my Shield tablet and see if I can clean up the profile a bit.
