### ISSUE TITLE
InControl Unity 5 + Triggers

### ISSUE THREAD

**Issue by Porrni** [pbhogan/InControl#193]
It seems like after updating to Unity 5 triggers don't work with Xbox 360 controllers on windows.

**Comment by Porrni** [comment]
Confirmed today that this is a windows related problem. The triggers do work on mac with 360 controller (using driver).

**Comment by pbhogan** [comment]
I got them to work, but triggers have always been very erratic on Windows with the xbox controller (unless you're using XInput).

Unity has just fixed a bunch of serious bugs related to this in the latest couple patches for 4.6. Those fixes aren't in 5 yet. I'm told they might land in a patch or in 5.1.
