### ISSUE TITLE
DeadZone?

### ISSUE THREAD

**Issue by cAyou66** [pbhogan/InControl#196]
Hi ! I would like to know how I can change the deadzone of our sticks. It seems that currently there is no deadzone at all (I barely touch the stick and my character moves), I've searched on the API and I've found some results about "deadzone" but I don't understand how I can change them.
Thanks !

**Comment by Treefire** [comment]
Hey,

I don't know if there is a built in deadzone function on inControl (I have never found it) but i handle my deadzones like the following:

float controller_deadzone = 0.25f; // Or whatever value you want your deadzone to be

// Then I check the magnitude of the vector2 of the stick against the deadzone
if (moveDirection.magnitude > controller_deadzone) {
    // Do your movement here
}

**Comment by pbhogan** [comment]
There is already a deadzone specified in each device profile, but you should be able to alter it by getting a control on a device and changing the LowerDeadZone and UpperDeadZone properties. The defaults are 0.2 and 0.9 respectively.

For the Github version you'll need to set it on both LeftStickX and LeftStickY individually. For the Asset Store version I believe you can set it directly on LeftStick.

**Comment by cAyou66** [comment]
Alright, thanks for this amazingly quick answer :)
