### ISSUE TITLE
CustomProfileExample: Instructions in Comment don't work

### ISSUE THREAD

**Issue by col000r** [pbhogan/InControl#199]
In the file it says: "or you can attach it yourself like so: InputManager.AttachDevice( new UnityInputDevice( "KeyboardAndMouseProfile" ) );"

This does not work. Console says: "Argument `#1' cannot convert `string' expression to type `InControl.UnityInputDeviceProfile'"

**Comment by pbhogan** [comment]
Sorry, that's a typo. It should be: 
```csharp
InputManager.AttachDevice( new UnityInputDevice( new KeyboardAndMouseProfile() ) );
```

If you absolutely have to convert from a string, this is what `InControlInputManager` does internally:
```csharp
var classType = Type.GetType( className );
if (classType == null)
{
	Debug.LogError( "Cannot find class for custom profile: " + className );
}
else
{
	var customProfileInstance = Activator.CreateInstance( classType ) as InputDeviceProfile;
	InputManager.AttachDevice( new UnityInputDevice( customProfileInstance ) );
}
```
