### ISSUE TITLE
XInputInterface.dll failing at x64

### ISSUE THREAD

**Issue by CarlosMangas** [pbhogan/InControl#200]
Whenever I start the game with the XInput option enabled I get this messages:

`Failed to load 'Assets/External Assets/InControl/Source/XInput/XInputInterface.dll', expected 64 bit architecture (IMAGE_FILE_MACHINE_AMD64), but was IMAGE_FILE_MACHINE_I386.`

`Assets/External Assets/InControl/Source/XInput/XInputInterface.dll.dll could not be found or is missing a dependency.`

I'm in a 64x Windows 7 compiling for Unity 5.

**Comment by ChrisNZL** [comment]
I had this too, but resolved by downloading the [latest XInput release](https://github.com/speps/XInputDotNet/releases) and replacing InControl's XInputInterface.dll file with the 64-bit version from the 64-bit XInput release zip.

And when building either 32-bit or 64-bit for Windows, be sure to put the correct XInputInterface.dll beside the game's exe too.

**Comment by pbhogan** [comment]
Yup, as mentioned on the documentation (http://www.gallantgames.com/pages/incontrol-xinput) you'll need to get the proper DLL. I'm going to try to include it in the package for Unity 5 now that plugins work in both the free and pro versions. I'm unsure of whether Unity 5 plugin inspector settings (http://docs.unity3d.com/Manual/PluginInspector.html) make it into packages though. I'll need to do some experimenting.

**Comment by pbhogan** [comment]
To be clear, if possible, I'll be able to include both the 32 and 64 bit versions in the package and Unity 5 should use it appropriately even for builds.

**Comment by CarlosMangas** [comment]
Thank you very much, I didn't see that section of the documentation, my bad..
