### ISSUE TITLE
New controller profile: GameCubeWinProfile.cs

### ISSUE THREAD

**Issue by ChrisNZL** [pbhogan/InControl#201]
Hello Patrick,

I've created a new profile for a GameCube USB controller adaptor on Windows. Could you add to InControl when you get the chance please?

[GameCubeWinProfile.cs](https://gist.github.com/ChrisNZL/5596b5596e0c0e60c0ed)

I know the joystick name "USB GamePad" is super generic but I worked with my customer to find all this joystick info, they say it's been working great for them.

Thanks

**Comment by pbhogan** [comment]
Thanks, I'll add it for now since nothing else clashes with that name.

**Comment by pbhogan** [comment]
Oh, do you happen to know exactly which adapter is being used for this?

**Comment by ChrisNZL** [comment]
My customer told me it was: Gamecube Controller Adapter for PC USB

Didn't mention a brand name though.

**Comment by ChrisNZL** [comment]
Customer has linked me this product page: [GC Controller Adapter for PC by Mayflash](http://www.amazon.com/GC-Controller-Adapter-for-PC/dp/B0089NVTDM)
