### ISSUE TITLE
New Android profile: IPEGA PG-9023

### ISSUE THREAD

**Issue by ChrisNZL** [pbhogan/InControl#202]
Hi Patrick,

I worked with a customer and got their [IPEGA PG-9023 controller](http://www.ipega.hk/index.php?option=com_phocagallery&view=detail&catid=11%3Abluetooth-game-controller&id=1100%3Abluetooth-stretch-controller&Itemid=4&lang=en) working on Android with Tallowmere.

[Device profile here.](https://gist.github.com/ChrisNZL/2ffa6b19d48d82096a59)

Cheers,
Chris

**Comment by pbhogan** [comment]
Thanks!
