### ISSUE TITLE
New Android profile: SteelSeries Stratus XL

### ISSUE THREAD

**Issue by ChrisNZL** [pbhogan/InControl#203]
Another profile: [SteelSeries Stratus XL](http://steelseries.com/products/controllers/stratus-xl-wireless-gaming-controller-for-ios) on Android.

However, no D-Pad support, not recognised as buttons nor analog, unless you have any ideas as what it could be? It's "Made For iPhone" if that helps at all, perhaps the D-Pad just isn't compatible with Android. I own this controller so can test things further if needed.

[Device profile here.](https://gist.github.com/ChrisNZL/09f3f612e89e9b508229)

Edit: Also worth noting that the Home/Guide button minimises the app, no control over it.

Thanks

**Comment by pbhogan** [comment]
I'm very surprised this actually works at all. I don't think they intend it to be Android compatible. I'll include it for now anyway since enough works to make it functional.
