### ISSUE TITLE
Updated to InControl 1.5.7, receiving Failed to load 'Assets/InControl/Plugins/x86/XInputInterface32.dll'

### ISSUE THREAD

**Issue by MadballNeek** [pbhogan/InControl#205]
After updating to InControl 1.5.7, I'm now receiving the following error upon starting the game within the Editor.

Failed to load 'Assets/InControl/Plugins/x86/XInputInterface32.dll', expected 64 bit architecture (IMAGE_FILE_MACHINE_AMD64), but was IMAGE_FILE_MACHINE_I386.
XInputDotNetPure.GamePad:GetState(PlayerIndex) (at Assets/InControl/Source/XInput/XInputDotNetPure/GamePad.cs:396)
XInputDotNetPure.GamePad:GetState(PlayerIndex) (at Assets/InControl/Source/XInput/XInputDotNetPure/GamePad.cs:393)
InControl.XInputDeviceManager:CheckPlatformSupport(ICollection`1) (at Assets/InControl/Source/XInput/XInputDeviceManager.cs:139)
InControl.XInputDeviceManager:Enable() (at Assets/InControl/Source/XInput/XInputDeviceManager.cs:157)
InControl.InputManager:SetupInternal() (at Assets/InControl/Source/InputManager.cs:102)
InControl.InControlManager:OnEnable() (at Assets/InControl/Source/Components/InControlManager.cs:38)
UnityEngine.Object:Instantiate(Object)
com.mindshaft.overtime.MainMenuRoot:Awake() (at Assets/Scripts/MainMenuRoot.cs:17)

**Comment by pbhogan** [comment]
For some reason DLL settings in the new Plugin Inspector don't survive packaging for the Asset Store. Please see instructions on how to correctly tag the DLLs here: http://www.gallantgames.com/pages/incontrol-xinput
