### ISSUE TITLE
Left and right triggers are not working

### ISSUE THREAD

**Issue by cAyou66** [pbhogan/InControl#206]
Hi there !
We are using InControl for our game indev, Subaeria, and we are experimenting some issue with the xbox controller.
On a new computer, with the controller recognized in windows (7, 8, 10 beta) everything works well except the left and right triggers. We looked to the settings menu on the controller on windows and  triggers are working. The trick for now to make triggers working is to re install controller drivers at this address:
https://www.microsoft.com/hardware/en-ca/d/xbox-360-controller-for-windows

It works but we can't ship the game with this issue. 
Have you experienced an issue like that before? Thanks !

**Comment by pbhogan** [comment]
What exactly do you mean by not working? Do you mean they cancel each other out or just don't respond at all? I've heard of the former but not the latter, at least not on the latest versions of Unity 4 and 5.

Either way, there have always been weird issues with Xbox 360 controllers (actually XInput controllers) and Unity. To this day they haven't quite resolved all the various bugs, and it usually affects the triggers in some way. The only reliable way to deal with this currently is to enable InControl's XInput support which circumvents Unity entirely: http://www.gallantgames.com/pages/incontrol-xinput

If you're still using this Github version of InControl, however, that could also be part of the problem. Since it is no longer maintained or supported, it isn't updated to deal with changes in Unity. Only the Asset Store version is maintained now.

**Comment by cAyou66** [comment]
They don't respond at all, but they work on the property window of the controller on Windows.

We are using rumble function, meaning we are using XInput (a version from the website, as the one coming with your plugin didn't work for us). I don't remember if I still use this version or asset store one, I will take look tomorrow morning.

Thanks !

**Comment by pbhogan** [comment]
Just a brief warning on the current version on the Asset Store, I found a critical bug affecting the XInput support this evening, so you'll want to avoid 1.5.7. The fix is submitted and will hopefully be approved speedily.

**Comment by cAyou66** [comment]
I'll wait for the patch so.

**Comment by cAyou66** [comment]
Ok I updated to the 1.5.8 version, I have one code upgrade issue.
It seems that you removed the InputControlType.LeftStickX (and others from the same category) from your plugin. Is there any workaround? Thanks.

**Comment by cAyou66** [comment]
fyi you can still access the LeftStickX from the ActiveDevice, but I can't anymore access to the LeftStickX from the GetControl function on the ActiveDevice class (because it's not anymore on your enum InputControlType).

**Comment by pbhogan** [comment]
Yes, this is a change to the API in 1.5. There is no way to get to LeftStickX through GetControl. You should either use InputDevice.LeftStickX or InputDevice.LeftStick.X

If you are trying to implement remapping by using GetControl, you should look at the bindings API (http://www.gallantgames.com/pages/incontrol-binding-actions-to-controls) or you'll need to manage your own enum.

**Comment by cAyou66** [comment]
Sad to hear. Why did you remove that functionnality? We are not remapping buttons (yet) but I'm using a public InputControlType so the game designer can choose what axis is used for controlling the character and stuff.

**Comment by pbhogan** [comment]
It better fits the bindings API to have the directions split out as LeftStickLeft, Right, Up and Down and allows a lot of other internal simplification.

For your purpose, it would be trivial for you to implement your own enum and a switch statement to go along with it. Although, it seems like overkill to expose that to the designer directly. It's something that is not adjusted much for a game, and if it needs to change it's a quick change in the code. It's just not really worth cramming additional complexity into InControl to support that.

**Comment by cAyou66** [comment]
Ok but why did you let the LeftStickX accessible directly from the ActiveDevice and not from the GetControl function? Everything is here except those axis. 

It seems that I will have to create my own tool to manage that, but it seems totally overkill for what I need.

**Comment by cAyou66** [comment]
btw I will let you know if it fixes the issue with left and right triggers.

**Comment by cAyou66** [comment]
Sidenote: you should add values to your enums, mostly when you might need to change them in the future. I've lost all my settings ingame because the InputControlType changed. For example, my Jump input was Action1, now it's D Pad button, or something like that.
