### ISSUE TITLE
New Android profile: Red Samurai Wireless Controller

### ISSUE THREAD

**Issue by ChrisNZL** [pbhogan/InControl#207]
Hi Patrick, can you please add this Red Samurai Wireless Controller profile?
- [C# code](https://gist.github.com/ChrisNZL/2c41cfbb6370753b6f83)
- [Amazon product page](http://www.amazon.com/dp/B00U5GDENO/)

(Can you please also add [Tallowmere](http://www.tallowmere.com/) to your [Wall of Games](http://www.gallantgames.com/pages/incontrol-wall-of-games)? Thanks~)

**Comment by pbhogan** [comment]
Thanks—it'll be in the next update. 

I'd be happy to put Tallowmere up on the wall. Do you have an image you'd like me to use?

**Comment by ChrisNZL** [comment]
[This image](http://cdn.akamai.steamstatic.com/steam/apps/340520/header.jpg?t=1431463674) please, cheers.

I'm still loving InControl - good stuff, keep it up!
