### ISSUE TITLE
New Android profile: Black Hawk Level Up controller

### ISSUE THREAD

**Issue by ChrisNZL** [pbhogan/InControl#209]
Hi Patrick, more Android profiles if you'd like to add!

Level Up Black Hawk controller:
- [C# profile](https://gist.github.com/ChrisNZL/fb2dc9cd3565f88758f3)
- [Product page](http://www.levelupworld.com/productos/gamepads/blackhawk_ps2-pc)

**Comment by pbhogan** [comment]
Added, thanks!

**Comment by ChrisNZL** [comment]
Ooops, had a mindblank there, this was for Windows, not Android (the source code doesn't lie mind you, just wanted to clear up any confusion)

**Comment by pbhogan** [comment]
Haha, yup. I got that. :)
