### ISSUE TITLE
New Android profile: Moga Pro Power

### ISSUE THREAD

**Issue by ChrisNZL** [pbhogan/InControl#210]
Another controller if you'd like to add-

Moga Pro Power:
- [C# profile](https://gist.github.com/ChrisNZL/fe9184ff699db2818c41)
- [Product page](http://www.mogaanywhere.com/controllers/propower)

This has the same button and analog IDs as the MogaHeroPowerAndroidProfile, just a different joystickName. I originally tried adding the name to the `JoystickNames` List like you've done on other profiles, and I also tried a regex entry of `"moga"`, but neither worked for my customer... Had to create a separate profile and it worked for them.

**Comment by pbhogan** [comment]
Added, thanks!
