### ISSUE TITLE
Conflicts everytime a pull is run

### ISSUE THREAD

**Issue by TheColorRed** [pbhogan/InControl#211]
Our game is using git source control and every time we play our game, it rewrites the file `VersionInfo.cs` and when we pull we get conflicts every time because the `Build` line gets updated. We then have to fix it everytime.

```
		public static VersionInfo InControlVersion()
		{
			return new VersionInfo() {
				Major = 1,
				Minor = 4,
				Patch = 4,
				Build = 4012
			};
		}
```

**Comment by pbhogan** [comment]
It sounds like you've pulled the entire InControl project into yours. You should only have the Assets/InControl folder included, not the Assets/Editor folder which includes a script that updates the build number during InControl development.
