### ISSUE TITLE
Updated/Fixed Profile for SteelSeries Stratus XL (Android)

### ISSUE THREAD

**Issue by artofcode** [pbhogan/InControl#213]
Besides being compatible with windows ( https://github.com/pbhogan/InControl/issues/212 ), I found that the included android profile ( https://github.com/pbhogan/InControl/issues/203 ) doesn't match the actual hardware. I believe that has something to do with it being the iOS version of the controller that was being used on an android device, which might explain that the d-pad wasn't working.

Here is an updated profile using the android/windows version of the controller.
https://gist.github.com/artofcode/78e2a5081a68f4f8e6ba

The only thing is that I couldn't find the back-button, which does work when connected to a Windows machine.

**Comment by pbhogan** [comment]
Thanks!
