### ISSUE TITLE
New profile: PlayStation 4 controller on Mac via Steam Link

### ISSUE THREAD

**Issue by ChrisNZL** [pbhogan/InControl#216]
Hi Patrick,

Could you add this profile please?
https://gist.github.com/ChrisNZL/0e1e772be11f2e18f704

Customer connected his PS4 controller to Steam Link using Bluetooth and was streaming my game from his Mac, and we got this profile going for him successfully.

Cheers,
Chris

**Comment by pbhogan** [comment]
Thanks, I'll get it in the next update.
