### ISSUE TITLE
Add API and UI to assist with custom user control mapping.

### ISSUE THREAD

**Issue by pbhogan** [pbhogan/InControl#7]
Most games need a controller customization screen.

**Comment by sbeca** [comment]
Hey @pbhogan, sorry to be annoying but I'm just wondering if there has been any update on this?

I have a client that would like this feature implemented and I'm working out what I need to do. I wouldn't necessarily need you to do the UI as I would have to most likely implement that myself but a way to query if any inputs (button or axis) on a controller are being used and if so, which one, would be very useful. Even better if you could do a way of remapping internally, again with no UI needed (at least for the first version).

Cheers - Scott

**Comment by pbhogan** [comment]
Actually, yes. It's currently in beta and will be in the Asset Store version soon. If you'd like to check it out, you can join the beta group here: https://groups.google.com/forum/#!forum/incontrol-beta

There is no UI component and I am unlikely to add one since it's so game specific, but the API is designed to take care of all the functional sides including detecting user presses during the rebinding process.

**Comment by sbeca** [comment]
Thank you @pbhogan for the update. I have applied for membership to the beta group and will check it out. Any idea how long before it is live?

**Comment by pbhogan** [comment]
It's basically ready. I want to do a little more documentation and such, but I'm planning to submit it Sunday if all goes well, so probably a week or so until it's on the Asset Store. Two weeks tops.
